### ISSUE TITLE
Page 70 - 'docker build -f Dockerfile.test -t 10.100.198.200:5000/books-ms-tests .' fails

### ISSUE THREAD

**Issue by michaelestrin** [vfarcic/ms-lifecycle#24]
gulp-yuidoc@0.1.2 node_modules/gulp-yuidoc
├── text-table@0.2.0
├── chalk@0.4.0 (has-color@0.1.7, ansi-styles@1.0.0, strip-ansi@0.1.1)
├── through2@0.4.1 (xtend@2.1.2, readable-stream@1.0.34)
├── gulp-util@2.2.20 (lodash._reinterpolate@2.4.1, minimist@0.2.0, chalk@0.5.1, vinyl@0.2.3, lodash.template@2.4.1, through2@0.5.1,
multipipe@0.1.2, dateformat@1.0.12)
├── vinyl-fs@0.1.4 (graceful-fs@2.0.3, map-stream@0.1.0, mkdirp@0.3.5, vinyl@0.2.3, glob-stream@3.1.18, glob-watcher@0.0.6)
└── yuidocjs@0.3.50 (graceful-fs@2.0.3, marked@0.2.10, minimatch@0.2.14, rimraf@2.5.4, express@3.1.2, yui@3.14.1)
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: ENOENT, rename '/tmp/053eb721967ff1d04dee652255581f3b/bower/deacf902f90ca6d3b27910fca875e706-71-NmJB8X/archive.tar.gz.1261675549'
    at Error (native)
The command '/bin/sh -c cd /source/client && npm install && bower install --allow-root --config.interactive=false -s' returned a non-zero code: 1
vagrant@cd:~/books-ms$

**Comment by vfarcic** [comment]
I just rerun the commands from the "Implementation of the Deployment Pipeline: Initial Stages" chapter and could not reproduce the problem you are facing. The image was built without any error.

The issue you reported might be a temporary glitch in npm that was resolved in the mean time. Can you please re-run it again and check whether it still fails. If it is still not working, it is probably somehow related to your laptop, network, or something else specific to your environment. In that case, maybe we can have a chat on Skype or HangOuts and share your screen. That way I might be able to find out what the problem is.

**Comment by michaelestrin** [comment]
Issue is reproducible.  Agree that it is likely related to my environment.

**Comment by michaelestrin** [comment]
Running by hand as described in that chapter consistently results in the aforementioned error.  However, it builds correctly when executed by Jenkins as described in the 'Clustering and Scaling Services' chapter.  Go figure.

**Comment by vfarcic** [comment]
The difference is that the command you executed manually runs in a loop
with the idea to test any change to FE while you're developing. Even though
tests are temporarily disabled, the loop is still there and needs to be
stopped with ctrl+c. The tests in Jenkins are one-off thing. They run once.
