### ISSUE TITLE
Error running 'vagrant up cd --provision'

### ISSUE THREAD

**Issue by rhdsmnd** [vfarcic/ms-lifecycle#32]
From "Implementation of the Deployment Pipeleine: Initial Stages":

Error when running "vagrant up cd --provision"

"W: GPG error: https://apt.dockerproject.org ubuntu-trusty InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY F76221572C52609D"

Seems like an issue with the docker public key.  Maybe a command needs to be added to ansible/vagrant?

Also, another error after:

"
cd: cannot stat ‘/vagrant/ansible/ansible.cfg’
cd: : No such file or directory
"

**Comment by rhdsmnd** [comment]
Full error log:

[out.txt](https://github.com/vfarcic/ms-lifecycle/files/1796189/out.txt)

**Comment by vfarcic** [comment]
I'm not sure what the problem is. I just tried it out and it worked. What confuses me is that `vagrant up cd` worked in your case and `vagrant up cd --provision` didn't. Both processes execute the same provisioning steps. Can you please destroy the VM (`vagrant destroy -f`), create it again (`vagrant up cd`), and let me know whether it worked. That way we'll discard that the problem is with your environment and is limited to the case when you're trying to bring up and provision a stopped VM.

**Comment by rhdsmnd** [comment]
Thanks it worked
